name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        mssql: [2017, 2019]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
      - uses: 280780363/sqlserver-action@v1.0
        with:
          accept eula: Y
          sa password: REL2021-mssql
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - env:
          MSSQL_DATABASE: sqlserver://sa:REL2021-mssql@localhost:1433
        run: |
          sleep 15
          go test -race ./...
