name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        mssql: [2017, 2019]
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:${{ matrix.mssql }}-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: REL2021-mssql
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run go test ./...
        env:
          MSSQL_DATABASE: sqlserver://sa:REL2021-mssql@localhost:1433
        run: |
          sleep 15
          go test -race -tags=all -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Codecov
        uses: codecov/codecov-action@v1
        if: matrix.mssql == '2019'
